export enum customErrorCodes {
	// AUTH
	INVALID_TOKEN = "INVALID_TOKEN",
	SESSION_ERROR = "SESSION_ERROR",
	WRONG_CREDENTIALS = "WRONG_CREDENTIALS",

	// MISSING
	USER_MISSING_FOR_ID = "USER_MISSING_FOR_ID",
	USER_MISSING_FOR_EMAIL = "USER_MISSING_FOR_EMAIL",

	// LOADING ERRORS
	COULD_NOT_LOAD_USER_DATA = "COULD_NOT_LOAD_USER_DATA",

	// VALIDATION
	ARGUMENT_VALIDATION_ERROR = "ARGUMENT_VALIDATION_ERROR",
	OPERATION_FOBRIDDEN = "OPERATION_FOBRIDDEN",

	// UNKNOWN
	SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"
}
